import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { JSX } from "react";

const inter: { className: string } = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>): JSX {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>КНИГОПОИСК</header>
        <main>{children}</main>
        <footer>footer</footer>
      </body>
    </html>
  );
}
