import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter: { className: string } = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app22"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>header222</header>
        <main>{children}</main>
        <footer>footer</footer>
      </body>
    </html>
  );
}
